// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6lM03KvMkPzcY7l7799LKxkhPL1QnmhM',
    appId: '1:739391181270:web:242f974173693b7631d477',
    messagingSenderId: '739391181270',
    projectId: 'fitcoach-62d1e',
    authDomain: 'fitcoach-62d1e.firebaseapp.com',
    storageBucket: 'fitcoach-62d1e.firebasestorage.app',
    measurementId: 'G-N9B2W2TBM0',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEv6nSHOhoVRwkoAK-yCb5fhpsx8FZP5g',
    appId: '1:739391181270:ios:3192496407845df231d477',
    messagingSenderId: '739391181270',
    projectId: 'fitcoach-62d1e',
    storageBucket: 'fitcoach-62d1e.firebasestorage.app',
    iosBundleId: 'com.example.fitcoach',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6lM03KvMkPzcY7l7799LKxkhPL1QnmhM',
    appId: '1:739391181270:web:69a16f81fbb153a631d477',
    messagingSenderId: '739391181270',
    projectId: 'fitcoach-62d1e',
    authDomain: 'fitcoach-62d1e.firebaseapp.com',
    storageBucket: 'fitcoach-62d1e.firebasestorage.app',
    measurementId: 'G-V69ERPD93F',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEv6nSHOhoVRwkoAK-yCb5fhpsx8FZP5g',
    appId: '1:739391181270:ios:3192496407845df231d477',
    messagingSenderId: '739391181270',
    projectId: 'fitcoach-62d1e',
    storageBucket: 'fitcoach-62d1e.firebasestorage.app',
    iosBundleId: 'com.example.fitcoach',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiC4OF3xWKQgmFqQMuHrCD7hlyHNSvUis',
    appId: '1:739391181270:android:ad9336bd10d65d1231d477',
    messagingSenderId: '739391181270',
    projectId: 'fitcoach-62d1e',
    storageBucket: 'fitcoach-62d1e.firebasestorage.app',
  );

}