// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZySLMc-H_BjpPDE-Why6F92Jr8nUaMHg',
    appId: '1:1007397700408:web:940009b060e085491437cd',
    messagingSenderId: '1007397700408',
    projectId: 'fitcoach-89ccb',
    authDomain: 'fitcoach-89ccb.firebaseapp.com',
    storageBucket: 'fitcoach-89ccb.firebasestorage.app',
    measurementId: 'G-9LGSXQJ9B8',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1ZJgAYdBDVHJigbgn0IM81Mqm3PVyRSc',
    appId: '1:1007397700408:ios:58bd0c80ecce72431437cd',
    messagingSenderId: '1007397700408',
    projectId: 'fitcoach-89ccb',
    storageBucket: 'fitcoach-89ccb.firebasestorage.app',
    iosBundleId: 'com.example.fitcoach',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZySLMc-H_BjpPDE-Why6F92Jr8nUaMHg',
    appId: '1:1007397700408:web:a3a29be4aa5f56661437cd',
    messagingSenderId: '1007397700408',
    projectId: 'fitcoach-89ccb',
    authDomain: 'fitcoach-89ccb.firebaseapp.com',
    storageBucket: 'fitcoach-89ccb.firebasestorage.app',
    measurementId: 'G-N92LTZCDW0',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1ZJgAYdBDVHJigbgn0IM81Mqm3PVyRSc',
    appId: '1:1007397700408:ios:58bd0c80ecce72431437cd',
    messagingSenderId: '1007397700408',
    projectId: 'fitcoach-89ccb',
    storageBucket: 'fitcoach-89ccb.firebasestorage.app',
    iosBundleId: 'com.example.fitcoach',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBR_YiYOCvJiiWba36HnRvBwrIHLaQmSB8',
    appId: '1:1007397700408:android:e043fc7559d0046f1437cd',
    messagingSenderId: '1007397700408',
    projectId: 'fitcoach-89ccb',
    storageBucket: 'fitcoach-89ccb.firebasestorage.app',
  );

}